version: '3'

services:
  postgres:
    image: postgres:14-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_WAREHOUSE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_WAREHOUSE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_WAREHOUSE_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_WAREHOUSE_USER}" ]
      interval: 5s
      retries: 5
    restart: on-failure
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: 'dpage/pgadmin4:6.1'  # latest image as of 2021-11-08
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mypgadmin:80/misc/ping"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "5050:80"
  metabase:
    image: metabase/metabase
    container_name: dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db  
  minio:
    image: 'bitnami/minio:2023.4.28'
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  postgres:
  pgadmin:
  minio: